name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ## thanks to https://github.com/exaexa/better-mff-thesis
  ##       and https://github.com/mff-cuni-cz/cuni-thesis-validator
  build:
    name: Build PDF and upload as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: Thesis
          path: Thesis.pdf
  


         


